---
- name: Backup web servers
  hosts: web
  tasks:
    - name: Set facts
      set_fact: 
        deploymentDate="{{lookup('pipe','date +%Y%m%d%H%M')}}"
        targetEnvironment="live"    
        deploymentApp = "OneClick"
        deploymentPath = ""
        backupPath = "C:\\inetpub\\00Backup"
    
        
    - name: Create 00Backup folder
      win_file:
        path: '{{backupPath}}'
        state: directory
        

    - name: Create {{backupPath}}\{{deploymentApp}} folder
      win_file:
        path: '{{backupPath}}\{{deploymentApp}}'
        state: directory        
        
    - name: Create {{backupPath}}\{{deploymentApp}}\{{deploymentApp}}{{deploymentDate}} folder for this backup
      win_file:
        path: '{{backupPath}}\{{deploymentApp}}{{deploymentDate}}'
        state: directory 

    # - name: Get backup
      # win_copy:
        # src:  C:\inetpub\wwwroot\{{deploymentApp}}\index.htm
        # dest: C:\inetpub\00Backup\{{deploymentApp}}{{deploymentDate}}\index.htm
        # ignore_errors: True 
        
    - name: Backup {{deploymentApp}}
      script: '{{powershellPath}}\backup.ps1  C:\inetpub\wwwroot\{{deploymentApp}}  C:\inetpub\00Backup\{{deploymentApp}}{{deploymentDate}} '
      
       
