---
- name: Backup web servers
  hosts: web
  tasks:
    - set_fact: deploymentDate="{{lookup('pipe','date +%Y%m%d%H%M')}}"
    - set_fact: targetEnvironment="live"    
    - set_fact: deploymentApp = "OneClick"
    - set_fact: deploymentPath = ""
    - set_fact: backupPath = "C:\inetpub\00Backup"
    
        
    - name: Create 00Backup folder
      win_file:
        path: {{backupPath}}
        state: directory
        

    - name: Create {{backupPath}}\{{deploymentApp}} folder
      win_file:
        path: {{backupPath}}\{{deploymentApp}}
        state: directory        
        
    - name: Create {{backupPath}}\{{deploymentApp}}\{{deploymentApp}}{{deploymentDate}} folder for this backup
      win_file:
        path: {{backupPath}}\{{deploymentApp}}{{deploymentDate}}
        state: directory 

    # - name: Get backup
      # win_copy:
        # src:  C:\inetpub\wwwroot\{{deploymentApp}}\index.htm
        # dest: C:\inetpub\00Backup\{{deploymentApp}}{{deploymentDate}}\index.htm
        # ignore_errors: True 
        
    - name: Backup {{deploymentApp}}
      win_shell:
      
       
