---
- name: check web servers are ready
  hosts: web 
  tasks:  
    - set_fact: 
      powershellPath: "c:\\inetpub\\powershellScripts"
    
    - name: ping servers
      win_ping:
        data: crash
 
    - name: Ensure "Web Server (IIS)" feature is installed
      win_feature: 
        name: WEB-SERVER
        state: present
      
    - name: Ensure IIS service is started
      win_service: 
        name: W3SVC
        state: started
   
    - name: Ensure Microsoft .Net Framework 4.5.2 is installed
      win_chocolatey:
        name: dotnet4.5.2
 
    - name: Create PowerShell folder
      win_file:
        path: '{{powershellPath}}'
        state: directory
      
    - name: Download powershell scritps
      win_get_url:
        url: 'https://github.com/mehrdud/ansible/blob/master/powershellScripts/backup.ps1'
        dest: '{{powershellPath}}\backup.ps1'
