---
- name: check web servers are ready
  hosts: web
  gather_facts: false
  tasks:
    - set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M')}}"
    - set_fact: targetEnvironment="live"
  
    - name: ping servers
      win_ping:
        data: crash
 
    - name: Ensure "Web Server (IIS)" feature is installed
      win_feature: 
        name: WEB-SERVER
        state: present
      
    - name: Ensure IIS service is started
      win_service: 
        name: W3SVC
        state: started
   
    - name: Ensure Microsoft .Net Framework 4.5.2 is installed
      win_chocolatey:
        name: dotnet4.5.2          
    
    - name: Create OneClick website folder
      win_file:
        path: C:\inetpub\wwwroot\OneClick
        state: directory
     
    - name: Create OneClick IIS WebSite 
      win_iis_website:
        name: "OneClick"
        state: started
        port: 80
        ip: 127.0.0.1
        hostname: OneClick
        application_pool: "OneClick"
        physical_path: C:\inetpub\wwwroot\OneClick
        
    - name: Create 00Backup folder
      win_file:
        path: C:\inetpub\00Backup
        state: directory
        

    - name: Create 00Backup\OneClick folder
      win_file:
        path: C:\inetpub\00Backup\OneClick
        state: directory        
        
    - name: Create 00Backup\OneClick\OneClick{{mydate}} folder for this backup
      win_file:
        path: C:\inetpub\00Backup\OneClick{{mydate}}
        state: directory 

    # - name: Get backup
      # win_copy:
        # src:  C:\inetpub\wwwroot\OneClick\index.htm
        # dest: C:\inetpub\00Backup\OneClick{{mydate}}\index.htm
        # ignore_errors: True
        
        
    - name: Download deployment package
      win_get_url:
         url: 'https://github.com/mehrdud/ansible/blob/master/DeploymentPackages/OneClick.zip'
         dest: C:\inetpub\wwwroot\OneClick\OneClick{{mydate}}.zip
    
    - name: Unzip deployment package
      win_unzip: 
        src: C:\inetpub\wwwroot\OneClick\OneClick{{mydate}}.zip
        dest: C:\inetpub\wwwroot\OneClick
    
    - name: Get config file 
      win_get_url:
         url: 'https://github.com/mehrdud/ansible/blob/master/DeploymentPackages/web.{{targetEnvironment}}.config'
         dest: C:\inetpub\wwwroot\OneClick\web.config
       
