---
- name: check web servers are ready
  hosts: web 
  tasks:
    - name: Set facts
      set_fact: 
        deploymentDate: "{{lookup('pipe','date +%Y%m%d%H%M')}}"
        targetEnvironment: "live"
        deploymentApp: "OneClick"
        IISPath: "C:\\inetpub\\wwwroot"
        downloadSource_Config : "https://raw.githubusercontent.com/mehrdud/ansible/master/DeploymentPackages"
        downloadSource_Site: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages"
        targetPort: 5050
        targetIP: ""
          
    - name: Create {{deploymentApp}} website folder
      win_file:
        path: "{{IISPath}}\\{{deploymentApp}}"
        state: directory
     
    - name: Create {{deploymentApp}} IIS WebSite 
      win_iis_website:
        name: "{{deploymentApp}}"
        state: started
        port: {{targetPort}}        
        physical_path: "{{IISPath}}\\{{deploymentApp}}"
        
    - name: Add Firewall rule to allow "{{deploymentApp}}" on TCP port {{targetPort}}
        action: win_firewall_rule
        args:
          name: "{{deploymentApp}}"
          enable: yes
          state: present
          localport: {{targetPort}}
          action: allow
          direction: In
          protocol: TCP
      
    - name: Download deployment package
      win_get_url:
         url: '{{downloadSource_Site}}/{{deploymentApp}}.zip'
         dest: '{{IISPath}}\{{deploymentApp}}\{{deploymentApp}}.zip'
    
    - name: Unzip deployment package
      win_unzip: 
        src: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        dest: "{{IISPath}}\\{{deploymentApp}}"
    
    - name: Remove downloaded file
      win_file:
        path: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        state: absent
    
    - name: Get config file 
      win_get_url:
         url: "{{downloadSource_Config}}/web.{{targetEnvironment}}.config"
         dest: "{{IISPath}}\\{{deploymentApp}}\\web.config"
       