---
- name: check web servers are ready
  hosts: web
  gather_facts: false
  tasks:
    - name: ping servers
      win_ping:
         data: crash
         
    - name: Ensure "Web Server (IIS)" feature is installed
      win_feature: 
       name: WEB-SERVER
       state: present
      
    - name: Ensure IIS service is running
      win_service: 
       name: W3SVC
       state: running