---
- name: check web servers are ready
  hosts: web
  gather_facts: false
  tasks:
    - name: ping servers
      win_ping:
        data: crash
         
    - name: Ensure "Web Server (IIS)" feature is installed
      win_feature: 
        name: WEB-SERVER
        state: present
      
    - name: Ensure IIS service is started
      win_service: 
        name: W3SVC
        state: started
   
    - name: Ensure Microsoft .Net Framework 4.5.2 is installed
      win_chocolatey:
        name: dotnet4.5.2         
    
    - name: Create OneClick website folder
      win_file:
        path: C:\inetpub\wwwroot\OneClick
        state: directory
     
    - name: Create OneClick IIS WebSite
      win_iis_webapplication:
        name: OneClick
        site: OneClick
        state: present
        PhysicalPath: C:\inetpub\wwwroot\OneClick
 
    
    - name: Copy OneClick zip file 
      win_copy:
        src: https://github.com/mehrdud/ansible/blob/master/DeploymentPackages/OneClick.zip
        dest: C:\inetpub\wwwroot\OneClick\OneClick.zip
 