---
- name: check web servers are ready
  hosts: web 
  tasks:
    - set_fact: deploymentDate="{{lookup('pipe','date +%Y%m%d%H%M')}}"
    - set_fact: targetEnvironment="live"
    - set_fact: deploymentApp = "{{OneClick}}"
          
    - name: Create {{deploymentApp}} website folder
      win_file:
        path: C:\inetpub\wwwroot\{{deploymentApp}}
        state: directory
     
    - name: Create {{deploymentApp}} IIS WebSite 
      win_iis_website:
        name: "{{deploymentApp}}"
        state: started
        port: 5050
        ip: 127.0.0.1
        hostname: {{deploymentApp}} 
        physical_path: C:\inetpub\wwwroot\{{deploymentApp}}        
        
    - name: Download deployment package
      win_get_url:
         url: 'https://github.com/mehrdud/ansible/blob/master/DeploymentPackages/{{deploymentApp}}.zip'
         dest: C:\inetpub\wwwroot\{{deploymentApp}}\{{deploymentApp}}.zip
    
    - name: Unzip deployment package
      win_unzip: 
        src: C:\inetpub\wwwroot\{{deploymentApp}}\{{deploymentApp}}.zip
        dest: C:\inetpub\wwwroot\{{deploymentApp}}
    
    - name: Get config file 
      win_get_url:
         url: 'https://github.com/mehrdud/ansible/blob/master/DeploymentPackages/web.{{targetEnvironment}}.config'
         dest: C:\inetpub\wwwroot\{{deploymentApp}}\web.config
       