---
- name: check web servers are ready
  hosts: web 
  tasks:
    - name: Set facts
      set_fact: 
        deploymentDate: "{{lookup('pipe','date +%Y%m%d%H%M')}}"
        targetEnvironment: "live"
        deploymentApp: "OneClick"
        IISPath: "C:\\inetpub\\wwwroot"
        downloadSource_Config : "https://raw.github.com/mehrdud/ansible/blob/master/DeploymentPackages"
        downloadSource_Site: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages"
          
    - name: Create {{deploymentApp}} website folder
      win_file:
        path: "{{IISPath}}\\{{deploymentApp}}"
        state: directory
     
    - name: Create {{deploymentApp}} IIS WebSite 
      win_iis_website:
        name: "{{deploymentApp}}"
        state: started
        port: 5050  
        physical_path: "{{IISPath}}\\{{deploymentApp}}"
        
    - name: Download deployment package
      win_get_url:
         url: '{{downloadSource_Site}}/{{deploymentApp}}.zip'
         dest: '{{IISPath}}\{{deploymentApp}}\{{deploymentApp}}.zip'
    
    - name: Unzip deployment package
      win_unzip: 
        src: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        dest: "{{IISPath}}\\{{deploymentApp}}"
    
    - name: Remove downloaded file
      win_file:
        path: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        state: absent
    
    - name: Get config file 
      win_get_url:
         url: '{{downloadSource_Config}}//web.{{targetEnvironment}}.config'
         dest: "{{IISPath}}\\{{deploymentApp}}\\web.config"
       