---
- name: Backup web servers
  hosts: web
  tasks:
    
    - name: include var file
      include_vars: 
         file: variables.yml
         
    - name: Create 00Backup folder
      win_file:
        path: '{{backupPath}}'
        state: directory   
        
    - name: Create backup folder
      win_file:
        path: '{{backupPath}}\{{item.name}}{{deploymentId}}'
        state: directory
      with_items:
        "{{deploymentPackages}}"        

    - name: Backup deploymentApp
      win_command: 'PowerShell.exe -File "{{powershellPath}}\\backup.ps1" {{item.folder}} {{backupPath}}\{{item.name}}{{deploymentId}} '
      with_items:
        "{{deploymentPackages}}"        
        