---     
- name: check web servers are ready
  hosts: web   
  
  tasks:
    - name: Set facts
      set_fact: 
        deploymentDate: "{{lookup('pipe','date +%Y%m%d%H%M')}}"
        targetEnvironment: "live"
        IISPath: "C:\\inetpub\\wwwroot"
        downloadSource_Config : "https://raw.githubusercontent.com/mehrdud/ansible/master/DeploymentPackages"
        downloadSource_Site: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages" 
        # deploymentPackages:  
          # - { name: 'ShopperPortal', folder: 'C:\\inetpub\\wwwroot\\ShopperPortal', ip: '', port: 5050}
          # - { name: 'ShopperAPI', folder: 'C:\\inetpub\\wwwroot\\ShopperAPI', ip: '', port: 5060}

    - name: Include vars of stuff.yml into the 'stuff' variable (2.2).
      include_vars:
        file: variables.yml
        name: deploymentPackages

    - name: Create IIS Folder
      win_file:
        path: "{{item.folder}}"
        state: directory              
      with_dict:
        "{{deploymentPackages}}"
    # - name: Create IIS Folder
      # win_file: 
        # path: "{{item}}"
        # state: directory 
        # with_items:
           # - four
           # - five
           # - six
        
        #"{{deployPacks}}"
          
     
    # - name: Create {{deploymentApp}} IIS WebSite 
      # win_iis_website:
        # name: "{{deploymentApp}}"
        # state: stopped
        # port: "{{targetPort| int}}"
        # physical_path: "{{IISPath}}\\{{deploymentApp}}"  
        
    # - name: Add Firewall rule to allow "{{deploymentApp}}" on TCP port "{{targetPort}}"
      # win_firewall_rule: 
        # name: "{{deploymentApp}}"
        # enable: yes
        # state: present
        # localport: "{{targetPort| int}}"
        # action: allow
        # direction: In
        # protocol: TCP
        # force: True
      
    # - name: Download deployment package
      # win_get_url:
         # url: '{{downloadSource_Site}}/{{deploymentApp}}.zip'
         # dest: '{{IISPath}}\{{deploymentApp}}\{{deploymentApp}}.zip'
    
    # - name: Unzip deployment package
      # win_unzip: 
        # src: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        # dest: "{{IISPath}}\\{{deploymentApp}}"
    
    # - name: Remove downloaded file
      # win_file:
        # path: "{{IISPath}}\\{{deploymentApp}}\\{{deploymentApp}}.zip"
        # state: absent
    
    # - name: Get config file 
      # win_get_url:
         # url: "{{downloadSource_Config}}/Web.{{targetEnvironment}}.config"
         # dest: "{{IISPath}}\\{{deploymentApp}}\\Web.config"
         
    # - name: Start {{deploymentApp}} IIS WebSite 
      # win_iis_website:
        # name: "{{deploymentApp}}"
        # state: started  
       