targetEnvironment: "live"

downloadSource_Config : "https://raw.githubusercontent.com/mehrdud/ansible/master/DeploymentPackages"
downloadSource_Site: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages" 
        
deploymentPackages:  
  - name: 'DarkCocoaPortal'
    folder: 'C:\inetpub\wwwroot\DarkCocoaPortal'
    ip: ''
    port: 5050
    packageName: "DarkCocoaPortal.zip"    
    sourcePackage: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages/DarkCocoaPortal/DarkCocoaPortal.zip"
    sourceConfigFile: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages/DarkCocoaPortal/DarkCocoaPortal.zip"
    
  - name: 'DarkCocoaReports'
    folder: 'C:\inetpub\wwwroot\DarkCocoaReports'
    ip: ''
    port: 5060
    packageName: "DarkCocoaReports.zip"    
    sourcePackage: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages/DarkCocoaPortal/DarkCocoaReports.zip"    
    sourceConfigFile: "https://github.com/mehrdud/ansible/raw/master/DeploymentPackages/DarkCocoaPortal/DarkCocoaReports.zip"