- Portal:
   sourceFolder: "DarkCocoaPortal"
   targetFolder: "DarkCocoaPortal"
   deploymentApp: "DarkCocoaPortal"
   config: "web"
   port: 5050 

- Reports: 
   sourceFolder: "DarkCoCoaReports"
   targetFolder: "DarkCoCoaReports"
   deploymentApp: "DarkCoCoaReports"
   config: "web"
   port: 5060